stages:
    - pnpm_build
    # - push_bundle

variables:
    MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true'
    MAVEN_CLI_OPTS: '-s ./settings.xml --batch-mode'
    FF_USE_FASTZIP: 'true' # enable fastzip - a faster zip implementation that also supports level configuration.

cache:
    paths:
        - node_modules/
        - .m2/repository/
        - dist/
        - index.html
    key: ${CI_BUILD_REF_NAME}

# Does not push to maven central
pnpm_build_dev:
    stage: pnpm_build
    image:
        name: node:18.16.0-bookworm
        entrypoint: [ '/bin/bash', '-c' ]
    # See https://docs.gitlab.com/ee/ci/yaml/#only-and-except-simplified
    only:
        refs:
            - pushes
    except:
        variables:
            - $RELEASE == "TRUE"
    script:
        - apt-get update
        - apt-get install -y maven
        # - npm install webpack --save-dev
        - npm install -g pnpm@6
        - pnpm install
        - pnpm -v
        - pnpm run build
        - /usr/share/maven/bin/mvn $MAVEN_CLI_OPTS clean install -Dci.version=${VERSION}-SNAPSHOT
        # So that the cache takes up less space
        - rm -rf .m2/repository/org/semoss
    artifacts:
        paths:
            - target/semossweb-${VERSION}-SNAPSHOT.war

# # Pushes to maven central
pnpm_build_deploy:
    stage: pnpm_build
    image:
        name: node:18.16.0-bookworm
        entrypoint: [ '/bin/bash', '-c' ]
    # See https://docs.gitlab.com/ee/ci/yaml/#only-and-except-simplified
    only:
        refs:
            - triggers
            - web
        variables:
            - $CI_COMMIT_BRANCH == "dev"
    except:
        variables:
            - $RELEASE == "TRUE"
    script:
        - apt-get update
        - apt-get install -y maven
        - apt-get install -y gnupg2
        - gpg2 --batch --import <(echo "$GPG_PRIVATE_KEY")
        - echo "keyserver keyserver.ubuntu.com" > ~/.gnupg/gpg.conf
        - gpg2 --refresh-key
        # - npm install webpack --save-dev
        - npm install -g pnpm@6
        - pnpm install
        - pnpm -v
        - pnpm run build
        - /usr/share/maven/bin/mvn $MAVEN_CLI_OPTS deploy -P deploy -Dci.version=${VERSION}-SNAPSHOT
        # So that the cache takes up less space
        - rm -rf .m2/repository/org/semoss
    artifacts:
        paths:
            - target/semossweb-${VERSION}-SNAPSHOT.war

# # Releases to maven central
# pnpm_build_release:
#     stage: pnpm_build
#     # Only release if explicitly triggered on web and the RELEASE variable is set to TRUE
#     only:
#         refs:
#             - web
#         variables:
#             - $RELEASE == "TRUE"
#     script:
#         - apt-get update
#         - apt-get install -y maven
#         - apt-get install -y gnupg2
#         - gpg2 --batch --import <(echo "$GPG_PRIVATE_KEY")
#         - echo "keyserver keyserver.ubuntu.com" > ~/.gnupg/gpg.conf
#         - gpg2 --refresh-key
#         # - npm install webpack --save-dev
#         - npm install -g pnpm
#         - pnpm install
#         - pnpm -v
#         - pnpm run build
#         - /usr/share/maven/bin/mvn $MAVEN_CLI_OPTS deploy -P deploy -Dci.version=${VERSION}
#         # So that the cache takes up less space
#         - rm -rf .m2/repository/org/semoss
#     artifacts:
#         paths:
#             - target/semossweb-${VERSION}.war

# #push bundle
# push_bundle:
#     stage: push_bundle
#     only:
#         variables:
#             - $SEMOSSWEB_BUNDLE == "TRUE"
#     except:
#         variables:
#             - $RELEASE == "TRUE"
#     script:
#         - mv /builds/semoss/SemossWeb/dist /builds/semoss/SemossWeb/_dist
#         - svn checkout --username ${SVN_WRITE_USER} --password ${SVN_WRITE_PASS} --force svn://107.170.10.188:8080/SemossWeb/${SEMOSSWEB_BUNDLE_BRANCH} /builds/semoss/SemossWeb
#         - svn delete /builds/semoss/SemossWeb/dist --force
#         - mv /builds/semoss/SemossWeb/_dist /builds/semoss/SemossWeb/dist
#         - svn propset svn:ignore -F .svnignore .
#         - svn status
#         - svn add --force .
#         - svn rm $( svn status | sed -e '/^!/!d' -e 's/^!//' ) || echo "Nothing to remove"
#         - svn status
#         - echo $(git log -1 --pretty=format:"%s (%an) %b") > /builds/message.txt
#         - svn commit  --username ${SVN_WRITE_USER} --password ${SVN_WRITE_PASS} --file /builds/message.txt
#         - rm /builds/message.txt
